
server:
  port: 8089
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/byron?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
    username: root
#  profiles:
#    active: test
  security:
    user:
      name: admin
      password: 123
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
  redis:
    database: 0
    host: localhost
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: 1ms
        max-idle: 8
        min-idle: 0
    timeout: 1000
  mvc:
    static-path-pattern: /static/**
logging:
  level:
    org.springframework: WARN
    org.spring.springboot.dao: warn
    com.example.demo.dao: debug
#  file: logs/spring-boot-logging.log
multipart-properties:
  filePathPrefix: http://www.baidu.com
  filePathSuffix: 宝贝





