
server:
  port: 8089
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/byron?useUnicode=true&characterEncoding=utf8&useSSL=false
    password: root
    username: root
#  profiles:
#    active: test
logging:
  level:
    org.springframework: WARN
    org.spring.springboot.dao: warn
    com.example.demo.dao: debug
#  file: logs/spring-boot-logging.log
multipart-properties:
  filePathPrefix: http://www.baidu.com
  filePathSuffix: 宝贝


