
server:
  port: 8089
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    id-type: 0
spring:
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true    # 序列化日期是是否以timestamps输出
      WRITE_BIGDECIMAL_AS_PLAIN: true    # 序列化BigDecimal时是输出原始数字还是科学计数，默认false，即以toPlainString()科学计数方式来输出
      WRITE_ENUMS_USING_INDEX: true      # 序列化枚举是否以ordinal()来输出，默认false
      FAIL_ON_EMPTY_BEANS: false         # 忽略无法转换的对象
      WRITE_NULL_MAP_VALUES: false
    default-property-inclusion: ALWAYS
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: true  # 允许对象忽略json中不存在的属性
    time-zone: Asia/Shanghai
    locale: zh_CN
  datasource:
    url: jdbc:mysql://localhost:3306/byron?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
#  profiles:
#    active: test
  security:
    user:
      name: admin
      password: 123
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html
  redis:
    database: 0
    host: localhost
    password: 123456
    jedis:
      pool:
        max-active: 200
        max-wait: 1ms
        max-idle: 8
        min-idle: 0
    timeout: 1000
  mvc:
    static-path-pattern: /static/**
  cache:
    cache-names: cacheValue
    type: redis
    redis:
      use-key-prefix: false
logging:
  level:
    org.springframework: WARN
    org.spring.springboot.dao: warn
    com.example.demo.dao: debug
  file: logs/spring-boot-logging.log
multipart-properties:
  filePathPrefix: http://www.baidu.com
  filePathSuffix: 宝贝
security:
  oauth2:
    client-id: client
    client-secret: 123456
    authorized-grant-types: password,refresh_token
  authorization:
    check-token-access: isAuthenticated()



